Ödev 1: Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5], dtype=int)

print("Bir boyutlu array:", array1)
print("Boyut:", array1.ndim)
print("Eleman sayısı:",array1.size)


Bir boyutlu array: [1 2 3 4 5]
Boyut: 1
Eleman sayısı: 5


Ödev 2: İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [4]:
array2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print("\nİki boyutlu array:")
print(array2)
print("\nBoyut:", array2.ndim)
print("Eleman sayısı:", array2.size)
print("Satır sayısı:", array2.shape[0])
print("Sütun sayısı:", array2.shape[1])


İki boyutlu array:
[[1 2 3]
 [4 5 6]]

Boyut: 2
Eleman sayısı: 6
Satır sayısı: 2
Sütun sayısı: 3


In [26]:
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)

print("\nÜç boyutlu array:\n", array3)
print("\nBoyut:", array3.ndim)
print("Eleman sayısı:", array3.size)
print("Satır sayısı:", array3.shape[1])
print("Sütun sayısı:", array3.shape[2])
print("Derinlik sayısı:", array3.shape[0])


Üç boyutlu array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Boyut: 3
Eleman sayısı: 8
Satır sayısı: 2
Sütun sayısı: 2
Derinlik sayısı: 2


 Ödev 3: Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

In [22]:
print("İki boyutlu array:\n", array2)
print("\nİki boyutlu arrayden [1, 2] elemanı:", array2[1, 2])

İki boyutlu array:
 [[1 2 3]
 [4 5 6]]

İki boyutlu arrayden [1, 2] elemanı: 6


In [23]:
print("İki boyutlu array:\n", array2)
print("\nİki boyutlu array dilimi:\n", array2[0:2, 1:3])

İki boyutlu array:
 [[1 2 3]
 [4 5 6]]

İki boyutlu array dilimi:
 [[2 3]
 [5 6]]


In [24]:
print("Üç boyutlu array:\n", array3)
print("\nÜç boyutlu arrayden [0, 1, 1] elemanı:", array3[0, 1, 1])

Üç boyutlu array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Üç boyutlu arrayden [0, 1, 1] elemanı: 4


In [25]:
print("Üç boyutlu array:\n", array3)
print("\nÜç boyutlu array dilimi:\n", array3[:, 0, :])

Üç boyutlu array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Üç boyutlu array dilimi:
 [[1 2]
 [5 6]]


Ödev 4:  Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [31]:
array0 = np.zeros((2, 3), dtype=int)
print("\nSıfırlardan oluşan array:\n", array0)

array11 = np.ones((2, 3), dtype=int)
print("\nBirlerden oluşan array:\n", array11)

#satır
array_birlesim = np.concatenate((array0, array11), axis=0)
print("\nBirleştirilmiş arrayler -satır olarak:\n", array_birlesim)

#sütün
array_birlesim_sutun = np.concatenate((array0, array11), axis=1)
print("\nBirleştirilmiş arrayler -sütun olarak:\n", array_birlesim_sutun)


Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]]

Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]]

Birleştirilmiş arrayler -satır olarak:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

Birleştirilmiş arrayler -sütun olarak:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
